// Code generated by ent, DO NOT EDIT.

package record

import (
	"time"
)

const (
	// Label holds the string label denoting the record type in the database.
	Label = "record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRemoteAddr holds the string denoting the remote_addr field in the database.
	FieldRemoteAddr = "remote_addr"
	// FieldDNSName holds the string denoting the dns_name field in the database.
	FieldDNSName = "dns_name"
	// FieldHTTPURL holds the string denoting the http_url field in the database.
	FieldHTTPURL = "http_url"
	// FieldHTTPMethod holds the string denoting the http_method field in the database.
	FieldHTTPMethod = "http_method"
	// FieldHTTPRaw holds the string denoting the http_raw field in the database.
	FieldHTTPRaw = "http_raw"
	// FieldJndiProtocol holds the string denoting the jndi_protocol field in the database.
	FieldJndiProtocol = "jndi_protocol"
	// FieldJndiPath holds the string denoting the jndi_path field in the database.
	FieldJndiPath = "jndi_path"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the record in the database.
	Table = "records"
)

// Columns holds all SQL columns for record fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldType,
	FieldRemoteAddr,
	FieldDNSName,
	FieldHTTPURL,
	FieldHTTPMethod,
	FieldHTTPRaw,
	FieldJndiProtocol,
	FieldJndiPath,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDNSName holds the default value on creation for the "dns_name" field.
	DefaultDNSName string
	// DefaultHTTPURL holds the default value on creation for the "http_url" field.
	DefaultHTTPURL string
	// DefaultHTTPMethod holds the default value on creation for the "http_method" field.
	DefaultHTTPMethod string
	// DefaultHTTPRaw holds the default value on creation for the "http_raw" field.
	DefaultHTTPRaw string
	// DefaultJndiProtocol holds the default value on creation for the "jndi_protocol" field.
	DefaultJndiProtocol string
	// DefaultJndiPath holds the default value on creation for the "jndi_path" field.
	DefaultJndiPath string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
