version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: hyuga_redis
    restart: always
    volumes:
      - "./deploy/redis:/data"

  hyuga:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyuga
    ports:
      - 80:8000
      - "53:53/udp"
    depends_on:
      - "redis"
