// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// SystemConfig is the predicate function for systemconfig builders.
type SystemConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
