// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hyuga/internal/db/ent/record"
	"hyuga/internal/db/ent/schema"
	"hyuga/internal/db/ent/systemconfig"
	"hyuga/internal/db/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescDNSName is the schema descriptor for dns_name field.
	recordDescDNSName := recordFields[4].Descriptor()
	// record.DefaultDNSName holds the default value on creation for the dns_name field.
	record.DefaultDNSName = recordDescDNSName.Default.(string)
	// recordDescHTTPURL is the schema descriptor for http_url field.
	recordDescHTTPURL := recordFields[5].Descriptor()
	// record.DefaultHTTPURL holds the default value on creation for the http_url field.
	record.DefaultHTTPURL = recordDescHTTPURL.Default.(string)
	// recordDescHTTPMethod is the schema descriptor for http_method field.
	recordDescHTTPMethod := recordFields[6].Descriptor()
	// record.DefaultHTTPMethod holds the default value on creation for the http_method field.
	record.DefaultHTTPMethod = recordDescHTTPMethod.Default.(string)
	// recordDescHTTPRaw is the schema descriptor for http_raw field.
	recordDescHTTPRaw := recordFields[7].Descriptor()
	// record.DefaultHTTPRaw holds the default value on creation for the http_raw field.
	record.DefaultHTTPRaw = recordDescHTTPRaw.Default.(string)
	// recordDescJndiProtocol is the schema descriptor for jndi_protocol field.
	recordDescJndiProtocol := recordFields[8].Descriptor()
	// record.DefaultJndiProtocol holds the default value on creation for the jndi_protocol field.
	record.DefaultJndiProtocol = recordDescJndiProtocol.Default.(string)
	// recordDescJndiPath is the schema descriptor for jndi_path field.
	recordDescJndiPath := recordFields[9].Descriptor()
	// record.DefaultJndiPath holds the default value on creation for the jndi_path field.
	record.DefaultJndiPath = recordDescJndiPath.Default.(string)
	// recordDescCreatedAt is the schema descriptor for created_at field.
	recordDescCreatedAt := recordFields[10].Descriptor()
	// record.DefaultCreatedAt holds the default value on creation for the created_at field.
	record.DefaultCreatedAt = recordDescCreatedAt.Default.(func() time.Time)
	// recordDescUpdatedAt is the schema descriptor for updated_at field.
	recordDescUpdatedAt := recordFields[11].Descriptor()
	// record.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	record.DefaultUpdatedAt = recordDescUpdatedAt.Default.(func() time.Time)
	// record.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	record.UpdateDefaultUpdatedAt = recordDescUpdatedAt.UpdateDefault.(func() time.Time)
	systemconfigFields := schema.SystemConfig{}.Fields()
	_ = systemconfigFields
	// systemconfigDescValue is the schema descriptor for value field.
	systemconfigDescValue := systemconfigFields[1].Descriptor()
	// systemconfig.DefaultValue holds the default value on creation for the value field.
	systemconfig.DefaultValue = systemconfigDescValue.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescToken is the schema descriptor for token field.
	userDescToken := userFields[4].Descriptor()
	// user.DefaultToken holds the default value on creation for the token field.
	user.DefaultToken = userDescToken.Default.(string)
	// userDescFromUser is the schema descriptor for from_user field.
	userDescFromUser := userFields[5].Descriptor()
	// user.DefaultFromUser holds the default value on creation for the from_user field.
	user.DefaultFromUser = userDescFromUser.Default.(string)
	// userDescInviteCode is the schema descriptor for invite_code field.
	userDescInviteCode := userFields[6].Descriptor()
	// user.DefaultInviteCode holds the default value on creation for the invite_code field.
	user.DefaultInviteCode = userDescInviteCode.Default.(func() uuid.UUID)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
