// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hyuga/internal/db/ent/systemconfig"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// SystemConfig is the model entity for the SystemConfig schema.
type SystemConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case systemconfig.FieldKey, systemconfig.FieldValue:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type SystemConfig", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemConfig fields.
func (sc *SystemConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sc.ID = int(value.Int64)
		case systemconfig.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				sc.Key = value.String
			}
		case systemconfig.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				sc.Value = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this SystemConfig.
// Note that you need to call SystemConfig.Unwrap() before calling this method if this SystemConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (sc *SystemConfig) Update() *SystemConfigUpdateOne {
	return (&SystemConfigClient{config: sc.config}).UpdateOne(sc)
}

// Unwrap unwraps the SystemConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sc *SystemConfig) Unwrap() *SystemConfig {
	_tx, ok := sc.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemConfig is not a transactional entity")
	}
	sc.config.driver = _tx.drv
	return sc
}

// String implements the fmt.Stringer.
func (sc *SystemConfig) String() string {
	var builder strings.Builder
	builder.WriteString("SystemConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sc.ID))
	builder.WriteString("key=")
	builder.WriteString(sc.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(sc.Value)
	builder.WriteByte(')')
	return builder.String()
}

// SystemConfigs is a parsable slice of SystemConfig.
type SystemConfigs []*SystemConfig

func (sc SystemConfigs) config(cfg config) {
	for _i := range sc {
		sc[_i].config = cfg
	}
}
