// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hyuga/internal/db/ent/systemconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemConfigCreate is the builder for creating a SystemConfig entity.
type SystemConfigCreate struct {
	config
	mutation *SystemConfigMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (scc *SystemConfigCreate) SetKey(s string) *SystemConfigCreate {
	scc.mutation.SetKey(s)
	return scc
}

// SetValue sets the "value" field.
func (scc *SystemConfigCreate) SetValue(s string) *SystemConfigCreate {
	scc.mutation.SetValue(s)
	return scc
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (scc *SystemConfigCreate) SetNillableValue(s *string) *SystemConfigCreate {
	if s != nil {
		scc.SetValue(*s)
	}
	return scc
}

// Mutation returns the SystemConfigMutation object of the builder.
func (scc *SystemConfigCreate) Mutation() *SystemConfigMutation {
	return scc.mutation
}

// Save creates the SystemConfig in the database.
func (scc *SystemConfigCreate) Save(ctx context.Context) (*SystemConfig, error) {
	var (
		err  error
		node *SystemConfig
	)
	scc.defaults()
	if len(scc.hooks) == 0 {
		if err = scc.check(); err != nil {
			return nil, err
		}
		node, err = scc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SystemConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = scc.check(); err != nil {
				return nil, err
			}
			scc.mutation = mutation
			if node, err = scc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(scc.hooks) - 1; i >= 0; i-- {
			if scc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = scc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, scc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*SystemConfig)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SystemConfigMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (scc *SystemConfigCreate) SaveX(ctx context.Context) *SystemConfig {
	v, err := scc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scc *SystemConfigCreate) Exec(ctx context.Context) error {
	_, err := scc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scc *SystemConfigCreate) ExecX(ctx context.Context) {
	if err := scc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scc *SystemConfigCreate) defaults() {
	if _, ok := scc.mutation.Value(); !ok {
		v := systemconfig.DefaultValue
		scc.mutation.SetValue(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scc *SystemConfigCreate) check() error {
	if _, ok := scc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SystemConfig.key"`)}
	}
	if _, ok := scc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SystemConfig.value"`)}
	}
	return nil
}

func (scc *SystemConfigCreate) sqlSave(ctx context.Context) (*SystemConfig, error) {
	_node, _spec := scc.createSpec()
	if err := sqlgraph.CreateNode(ctx, scc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (scc *SystemConfigCreate) createSpec() (*SystemConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemConfig{config: scc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: systemconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: systemconfig.FieldID,
			},
		}
	)
	if value, ok := scc.mutation.Key(); ok {
		_spec.SetField(systemconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := scc.mutation.Value(); ok {
		_spec.SetField(systemconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// SystemConfigCreateBulk is the builder for creating many SystemConfig entities in bulk.
type SystemConfigCreateBulk struct {
	config
	builders []*SystemConfigCreate
}

// Save creates the SystemConfig entities in the database.
func (sccb *SystemConfigCreateBulk) Save(ctx context.Context) ([]*SystemConfig, error) {
	specs := make([]*sqlgraph.CreateSpec, len(sccb.builders))
	nodes := make([]*SystemConfig, len(sccb.builders))
	mutators := make([]Mutator, len(sccb.builders))
	for i := range sccb.builders {
		func(i int, root context.Context) {
			builder := sccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sccb *SystemConfigCreateBulk) SaveX(ctx context.Context) []*SystemConfig {
	v, err := sccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sccb *SystemConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := sccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccb *SystemConfigCreateBulk) ExecX(ctx context.Context) {
	if err := sccb.Exec(ctx); err != nil {
		panic(err)
	}
}
