@Host=api.hyuga.io
@Port=5000

#### Index
GET http://{{Host}}:{{Port}}/

## Index return-----------------
{   
    "code": 200,
    "message": "OK",
    "data": {"Server": "Hyuga"},
    "success": true
}

## Index return-----------------


#### CreateUser
POST http://{{Host}}:{{Port}}/v1/users

## CreateUser return-----------------
{
    "code": 200,
    "message": "OK",
    "data": {
        "token": "testtoken",
        "identity": "test.hyuga.io"
    },
    "success": true
}

## CreateUser return-----------------


#### Records
GET http://{{Host}}:{{Port}}/v1/records?type=dns&token=testtoken&filter=

## HTTP Records return-----------------
{
  "code": 200,
  "message": "OK",
  "data": [
    {
      "cookies": "",
      "method": "GET",
      "remoteAddr": "127.0.0.1:51784",
      "ts": "1598789985898214000",
      "url": "/v1/records?type=http\u0026token=testtoken"
    }
  ],
  "success": true
}

## DNS Records return-----------------
{
  "code": 200,
  "message": "OK",
  "data": [
    {
      "name": "test.hyuga.io.",
      "remoteAddr": "127.0.0.1:54517",
      "ts": "1598862979435977000"
    }
  ],
  "success": true
}
## Records return-----------------
