# vscode 安装 `REST Client` 扩展
@Host=api.hyuga.io
@Port=5000
@domain=q9ky.hyuga.io
@token=63CgS2DVOKdMpLa67ubvSsQBzG7u9VlLw8PfV23jBhDOZ8yQFwCcVDh48H0WZ599
@identity=q9ky

#### Index
GET http://{{Host}}:{{Port}}/

## Index return-----------------
{   
    "code": 200,
    "message": "OK",
    "data": {"Server": "Hyuga"},
    "success": true
}

## Index return-----------------


#### CreateUser
POST http://{{Host}}:{{Port}}/v1/users

## CreateUser return-----------------
{
    "code": 200,
    "message": "OK",
    "data": {
        "token": "testtoken",
        "identity": "test.hyuga.io"
    },
    "success": true
}

## CreateUser return-----------------


#### Get User DNSRebinding
GET http://{{Host}}:{{Port}}/v1/users/{{identity}}/dns-rebinding
Content-Type: application/json

{
  "token": "{{token}}"
}

## Get-User-DNSRebinding return-----------------
{
    "code": 200,
    "message": "OK",
    "data": {
      "rebinding_hosts": ["127.0.0.1", "192.168.1.1"]
    },
    "success": true
}

## Get-User-DNSRebinding return-----------------


#### Set User DNSRebinding
POST http://{{Host}}:{{Port}}/v1/users/{{identity}}/dns-rebinding
Content-Type: application/json

{
  "token": "{{token}}",
  "hosts":["127.0.0.1", "192.168.1.1"]
}


## DNSRebinding return-----------------
{
    "code": 200,
    "message": "OK",
    "data": null,
    "success": true
}

## DNSRebinding return-----------------



#### Records
GET http://{{Host}}:{{Port}}/v1/records?type=dns&token={{token}}&filter=

## HTTP Records return-----------------
{
  "code": 200,
  "message": "OK",
  "data": [
    {
      "cookies": "",
      "method": "GET",
      "remoteAddr": "127.0.0.1:51784",
      "ts": "1598789985898214000",
      "url": "/v1/records?type=http\u0026token=testtoken"
    }
  ],
  "success": true
}

## DNS Records return-----------------
{
  "code": 200,
  "message": "OK",
  "data": [
    {
      "name": "test.hyuga.io.",
      "remoteAddr": "127.0.0.1:54517",
      "ts": "1598862979435977000"
    }
  ],
  "success": true
}
## Records return-----------------
