name: Release Hyuga

on:
  push:
    tags:
      - v*
  release:
    types: [published]

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare release environment
    runs-on: ubuntu-latest
    steps:
      - run: env

  build-binary:
    name: Build binary
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            arch: amd64
            output: hyuga-windows-amd64.exe
          - os: darwin
            arch: amd64
            output: hyuga-darwin-amd64
          - os: darwin
            arch: arm64
            output: hyuga-darwin-arm64
          - os: linux
            arch: amd64
            output: hyuga-linux-amd64
          - os: linux
            arch: arm64
            output: hyuga-linux-arm64
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install && npm run build
        working-directory: frontend
      - run: mv frontend/dist  internal/handler/dist
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - run: go build -trimpath -ldflags "-w -s -extldflags '-static'" -o target/${{ matrix.output }}
      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/*

  collect-release:
    name: Collect and release
    needs: [build-binary]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: ls -al target && ls -R target/ && file target/
      - uses: actions/upload-artifact@v3
        with:
          name: target-release
          path: target/*

      # release assets
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*
